version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: toor
    networks:
      - broker_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d monitor"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - broker_network

  pinger:
    build:
      context: ./pinger
      dockerfile: Dockerfile
    container_name: pinger
    ports:
      - "6767:6767"
    depends_on:
      rabbitmq:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      INTERVAL: 60
      INPUT_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/monitor
      NOTIFY_ALWAYS: 0
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: root
      RABBITMQ_PASS: toor
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6767/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - broker_network

  llm_service:
    build:
      context: ./LLM_service
      dockerfile: Dockerfile
    container_name: llm_service
    ports:
      - "6868:6868"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - broker_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6868/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  tg_service:
    build:
      context: ./notifier-service/tg-bot
      dockerfile: Dockerfile
    container_name: tg_service
    ports:
      - "6966:6966"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      TG_TOKEN: 8368944259:AAHj-ivSsU-6GVV7nG4Ai1KFpNT6tKzIemM
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      LOG_LEVEL: INFO
    networks:
      - broker_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6966/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - broker_network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: monitor
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query=SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - broker_network

  api_service:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - broker_network
    environment:
      INPUT_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/monitor
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend/pingtower-flow
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://api_service:8000
    ports:
      - "8080:8080"
    depends_on:
      api_service:
        condition: service_healthy
    networks:
      - broker_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  broker_network:
    driver: bridge
